---
title: "Explore the data of Wang 2024"
author: "Wei Sun"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: journal
    highlight: tango
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: false
    number_sections: false
  df_print: paged
---

# libraries

```{r load_libraries, warning = FALSE, message = FALSE}
library(dplyr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(data.table)
library(readxl)
library(Matrix)
```


## Read in target gene annoation
```{r}
cd8 = readRDS("GSE272993_cd8_nn_labeled_FINAL.RDS")
dim(cd8)
slotNames(cd8)

Assays(cd8)

rna = GetAssayData(cd8[["RNA"]], layer = "count")
adt = GetAssayData(cd8[["ADT"]])
dim(rna)
dim(adt)

class(rna)
class(adt)

rna[101:102,1:3]
adt[1:2,1:3]

meta_df <- cd8@meta.data
dim(meta_df)
meta_df[1:2,]

table(colnames(adt) %in% rownames(meta_df))
table(colnames(rna) == rownames(meta_df))
```

## export data

```{r}
setwd("data_from_RDS")

writeMM(rna, file = "rna_counts.mtx")
write.table(rownames(rna), file = "genes_rna.txt", 
            quote = FALSE, row.names = FALSE, col.names = FALSE)
write.table(colnames(rna), file = "cells_rna.txt", 
            quote = FALSE, row.names = FALSE, col.names = FALSE)

write.csv(as.data.frame(adt), file = "adt_values.csv")

write.table(rownames(adt), file = "genes_adt.txt", 
            quote = FALSE, row.names = FALSE, col.names = FALSE)
write.table(colnames(adt), file = "cells_adt.txt", 
            quote = FALSE, row.names = FALSE, col.names = FALSE)

write.csv(cd8@meta.data, file = "cell_metadata.csv", row.names = TRUE)

```

```{r}
gc()
sessionInfo()
```

